/*
 * PotatoVN.Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using PotatoVN.Client.Client;
using PotatoVN.Client.Model;

namespace PotatoVN.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IGalgameApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 删除用户的所有游戏
        /// </summary>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        void GalgameDelete();

        /// <summary>
        /// 删除用户的所有游戏
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> GalgameDeleteWithHttpInfo();
        /// <summary>
        /// 获取已删除的galgame列表
        /// </summary>
        /// <remarks>
        /// 获取删除时间严格晚于给定时间戳的galgame列表
        /// </remarks>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="timestamp"></param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <returns>GalgameDeletedDtoPagedResult</returns>
        GalgameDeletedDtoPagedResult GalgameDeletedGet(long timestamp, int? pageIndex = default(int?), int? pageSize = default(int?));

        /// <summary>
        /// 获取已删除的galgame列表
        /// </summary>
        /// <remarks>
        /// 获取删除时间严格晚于给定时间戳的galgame列表
        /// </remarks>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="timestamp"></param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <returns>ApiResponse of GalgameDeletedDtoPagedResult</returns>
        ApiResponse<GalgameDeletedDtoPagedResult> GalgameDeletedGetWithHttpInfo(long timestamp, int? pageIndex = default(int?), int? pageSize = default(int?));
        /// <summary>
        /// 删除游戏
        /// </summary>
        /// <remarks>
        /// 只能删除自己的游戏
        /// </remarks>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="galgameId"></param>
        /// <returns></returns>
        void GalgameGalgameIdDelete(int galgameId);

        /// <summary>
        /// 删除游戏
        /// </summary>
        /// <remarks>
        /// 只能删除自己的游戏
        /// </remarks>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="galgameId"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> GalgameGalgameIdDeleteWithHttpInfo(int galgameId);
        /// <summary>
        /// 添加游玩记录或游玩时长
        /// </summary>
        /// <remarks>
        /// 若已经有当天游戏的记录，则累加上去
        /// </remarks>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="galgameId"></param>
        /// <param name="playLogDto"> (optional)</param>
        /// <returns>GalgameDto</returns>
        GalgameDto GalgameGalgameIdPlaylogPatch(int galgameId, PlayLogDto? playLogDto = default(PlayLogDto?));

        /// <summary>
        /// 添加游玩记录或游玩时长
        /// </summary>
        /// <remarks>
        /// 若已经有当天游戏的记录，则累加上去
        /// </remarks>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="galgameId"></param>
        /// <param name="playLogDto"> (optional)</param>
        /// <returns>ApiResponse of GalgameDto</returns>
        ApiResponse<GalgameDto> GalgameGalgameIdPlaylogPatchWithHttpInfo(int galgameId, PlayLogDto? playLogDto = default(PlayLogDto?));
        /// <summary>
        /// 获取galgame列表
        /// </summary>
        /// <remarks>
        /// 获取最后一次更新时间严格晚于给定时间戳的galgame列表
        /// </remarks>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="timestamp"></param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <returns>GalgameDtoPagedResult</returns>
        GalgameDtoPagedResult GalgameGet(long timestamp, int? pageIndex = default(int?), int? pageSize = default(int?));

        /// <summary>
        /// 获取galgame列表
        /// </summary>
        /// <remarks>
        /// 获取最后一次更新时间严格晚于给定时间戳的galgame列表
        /// </remarks>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="timestamp"></param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <returns>ApiResponse of GalgameDtoPagedResult</returns>
        ApiResponse<GalgameDtoPagedResult> GalgameGetWithHttpInfo(long timestamp, int? pageIndex = default(int?), int? pageSize = default(int?));
        /// <summary>
        /// 新建或更新galgame
        /// </summary>
        /// <remarks>
        /// 所有字段均可选，覆盖原字段 &lt;br /&gt;&lt;b&gt;若Id没有填，则认为是新建galgame&lt;/b&gt;&lt;br /&gt;  务必注意字段是覆盖的，意味着游玩时间记录会覆盖掉原记录，若需要追加记录请使用[PATCH] /galgame/{id}/playlog &lt;br /&gt;
        /// </remarks>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="galgameUpdateDto"> (optional)</param>
        /// <returns>GalgameDto</returns>
        GalgameDto GalgamePatch(GalgameUpdateDto? galgameUpdateDto = default(GalgameUpdateDto?));

        /// <summary>
        /// 新建或更新galgame
        /// </summary>
        /// <remarks>
        /// 所有字段均可选，覆盖原字段 &lt;br /&gt;&lt;b&gt;若Id没有填，则认为是新建galgame&lt;/b&gt;&lt;br /&gt;  务必注意字段是覆盖的，意味着游玩时间记录会覆盖掉原记录，若需要追加记录请使用[PATCH] /galgame/{id}/playlog &lt;br /&gt;
        /// </remarks>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="galgameUpdateDto"> (optional)</param>
        /// <returns>ApiResponse of GalgameDto</returns>
        ApiResponse<GalgameDto> GalgamePatchWithHttpInfo(GalgameUpdateDto? galgameUpdateDto = default(GalgameUpdateDto?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IGalgameApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 删除用户的所有游戏
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task GalgameDeleteAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 删除用户的所有游戏
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> GalgameDeleteWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 获取已删除的galgame列表
        /// </summary>
        /// <remarks>
        /// 获取删除时间严格晚于给定时间戳的galgame列表
        /// </remarks>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="timestamp"></param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GalgameDeletedDtoPagedResult</returns>
        System.Threading.Tasks.Task<GalgameDeletedDtoPagedResult> GalgameDeletedGetAsync(long timestamp, int? pageIndex = default(int?), int? pageSize = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 获取已删除的galgame列表
        /// </summary>
        /// <remarks>
        /// 获取删除时间严格晚于给定时间戳的galgame列表
        /// </remarks>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="timestamp"></param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GalgameDeletedDtoPagedResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<GalgameDeletedDtoPagedResult>> GalgameDeletedGetWithHttpInfoAsync(long timestamp, int? pageIndex = default(int?), int? pageSize = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 删除游戏
        /// </summary>
        /// <remarks>
        /// 只能删除自己的游戏
        /// </remarks>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="galgameId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task GalgameGalgameIdDeleteAsync(int galgameId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 删除游戏
        /// </summary>
        /// <remarks>
        /// 只能删除自己的游戏
        /// </remarks>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="galgameId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> GalgameGalgameIdDeleteWithHttpInfoAsync(int galgameId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 添加游玩记录或游玩时长
        /// </summary>
        /// <remarks>
        /// 若已经有当天游戏的记录，则累加上去
        /// </remarks>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="galgameId"></param>
        /// <param name="playLogDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GalgameDto</returns>
        System.Threading.Tasks.Task<GalgameDto> GalgameGalgameIdPlaylogPatchAsync(int galgameId, PlayLogDto? playLogDto = default(PlayLogDto?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 添加游玩记录或游玩时长
        /// </summary>
        /// <remarks>
        /// 若已经有当天游戏的记录，则累加上去
        /// </remarks>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="galgameId"></param>
        /// <param name="playLogDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GalgameDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<GalgameDto>> GalgameGalgameIdPlaylogPatchWithHttpInfoAsync(int galgameId, PlayLogDto? playLogDto = default(PlayLogDto?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 获取galgame列表
        /// </summary>
        /// <remarks>
        /// 获取最后一次更新时间严格晚于给定时间戳的galgame列表
        /// </remarks>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="timestamp"></param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GalgameDtoPagedResult</returns>
        System.Threading.Tasks.Task<GalgameDtoPagedResult> GalgameGetAsync(long timestamp, int? pageIndex = default(int?), int? pageSize = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 获取galgame列表
        /// </summary>
        /// <remarks>
        /// 获取最后一次更新时间严格晚于给定时间戳的galgame列表
        /// </remarks>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="timestamp"></param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GalgameDtoPagedResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<GalgameDtoPagedResult>> GalgameGetWithHttpInfoAsync(long timestamp, int? pageIndex = default(int?), int? pageSize = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 新建或更新galgame
        /// </summary>
        /// <remarks>
        /// 所有字段均可选，覆盖原字段 &lt;br /&gt;&lt;b&gt;若Id没有填，则认为是新建galgame&lt;/b&gt;&lt;br /&gt;  务必注意字段是覆盖的，意味着游玩时间记录会覆盖掉原记录，若需要追加记录请使用[PATCH] /galgame/{id}/playlog &lt;br /&gt;
        /// </remarks>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="galgameUpdateDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GalgameDto</returns>
        System.Threading.Tasks.Task<GalgameDto> GalgamePatchAsync(GalgameUpdateDto? galgameUpdateDto = default(GalgameUpdateDto?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 新建或更新galgame
        /// </summary>
        /// <remarks>
        /// 所有字段均可选，覆盖原字段 &lt;br /&gt;&lt;b&gt;若Id没有填，则认为是新建galgame&lt;/b&gt;&lt;br /&gt;  务必注意字段是覆盖的，意味着游玩时间记录会覆盖掉原记录，若需要追加记录请使用[PATCH] /galgame/{id}/playlog &lt;br /&gt;
        /// </remarks>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="galgameUpdateDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GalgameDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<GalgameDto>> GalgamePatchWithHttpInfoAsync(GalgameUpdateDto? galgameUpdateDto = default(GalgameUpdateDto?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IGalgameApi : IGalgameApiSync, IGalgameApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class GalgameApi : IDisposable, IGalgameApi
    {
        private PotatoVN.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="GalgameApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public GalgameApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GalgameApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public GalgameApi(string basePath)
        {
            this.Configuration = PotatoVN.Client.Client.Configuration.MergeConfigurations(
                PotatoVN.Client.Client.GlobalConfiguration.Instance,
                new PotatoVN.Client.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new PotatoVN.Client.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = PotatoVN.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GalgameApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public GalgameApi(PotatoVN.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = PotatoVN.Client.Client.Configuration.MergeConfigurations(
                PotatoVN.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new PotatoVN.Client.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = PotatoVN.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GalgameApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public GalgameApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GalgameApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public GalgameApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = PotatoVN.Client.Client.Configuration.MergeConfigurations(
                PotatoVN.Client.Client.GlobalConfiguration.Instance,
                new PotatoVN.Client.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new PotatoVN.Client.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = PotatoVN.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GalgameApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public GalgameApi(HttpClient client, PotatoVN.Client.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = PotatoVN.Client.Client.Configuration.MergeConfigurations(
                PotatoVN.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new PotatoVN.Client.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = PotatoVN.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GalgameApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public GalgameApi(PotatoVN.Client.Client.ISynchronousClient client, PotatoVN.Client.Client.IAsynchronousClient asyncClient, PotatoVN.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = PotatoVN.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public PotatoVN.Client.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public PotatoVN.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public PotatoVN.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public PotatoVN.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public PotatoVN.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// 删除用户的所有游戏 
        /// </summary>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        public void GalgameDelete()
        {
            GalgameDeleteWithHttpInfo();
        }

        /// <summary>
        /// 删除用户的所有游戏 
        /// </summary>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        public PotatoVN.Client.Client.ApiResponse<Object> GalgameDeleteWithHttpInfo()
        {
            PotatoVN.Client.Client.RequestOptions localVarRequestOptions = new PotatoVN.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = PotatoVN.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PotatoVN.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (oauth2) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/galgame", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GalgameDelete", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 删除用户的所有游戏 
        /// </summary>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task GalgameDeleteAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            await GalgameDeleteWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// 删除用户的所有游戏 
        /// </summary>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<PotatoVN.Client.Client.ApiResponse<Object>> GalgameDeleteWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            PotatoVN.Client.Client.RequestOptions localVarRequestOptions = new PotatoVN.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = PotatoVN.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PotatoVN.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (oauth2) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/galgame", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GalgameDelete", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 获取已删除的galgame列表 获取删除时间严格晚于给定时间戳的galgame列表
        /// </summary>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="timestamp"></param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <returns>GalgameDeletedDtoPagedResult</returns>
        public GalgameDeletedDtoPagedResult GalgameDeletedGet(long timestamp, int? pageIndex = default(int?), int? pageSize = default(int?))
        {
            PotatoVN.Client.Client.ApiResponse<GalgameDeletedDtoPagedResult> localVarResponse = GalgameDeletedGetWithHttpInfo(timestamp, pageIndex, pageSize);
            return localVarResponse.Data;
        }

        /// <summary>
        /// 获取已删除的galgame列表 获取删除时间严格晚于给定时间戳的galgame列表
        /// </summary>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="timestamp"></param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <returns>ApiResponse of GalgameDeletedDtoPagedResult</returns>
        public PotatoVN.Client.Client.ApiResponse<GalgameDeletedDtoPagedResult> GalgameDeletedGetWithHttpInfo(long timestamp, int? pageIndex = default(int?), int? pageSize = default(int?))
        {
            PotatoVN.Client.Client.RequestOptions localVarRequestOptions = new PotatoVN.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = PotatoVN.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PotatoVN.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(PotatoVN.Client.Client.ClientUtils.ParameterToMultiMap("", "timestamp", timestamp));
            if (pageIndex != null)
            {
                localVarRequestOptions.QueryParameters.Add(PotatoVN.Client.Client.ClientUtils.ParameterToMultiMap("", "pageIndex", pageIndex));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(PotatoVN.Client.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }

            // authentication (oauth2) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GalgameDeletedDtoPagedResult>("/galgame/deleted", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GalgameDeletedGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 获取已删除的galgame列表 获取删除时间严格晚于给定时间戳的galgame列表
        /// </summary>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="timestamp"></param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GalgameDeletedDtoPagedResult</returns>
        public async System.Threading.Tasks.Task<GalgameDeletedDtoPagedResult> GalgameDeletedGetAsync(long timestamp, int? pageIndex = default(int?), int? pageSize = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            PotatoVN.Client.Client.ApiResponse<GalgameDeletedDtoPagedResult> localVarResponse = await GalgameDeletedGetWithHttpInfoAsync(timestamp, pageIndex, pageSize, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// 获取已删除的galgame列表 获取删除时间严格晚于给定时间戳的galgame列表
        /// </summary>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="timestamp"></param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GalgameDeletedDtoPagedResult)</returns>
        public async System.Threading.Tasks.Task<PotatoVN.Client.Client.ApiResponse<GalgameDeletedDtoPagedResult>> GalgameDeletedGetWithHttpInfoAsync(long timestamp, int? pageIndex = default(int?), int? pageSize = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            PotatoVN.Client.Client.RequestOptions localVarRequestOptions = new PotatoVN.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = PotatoVN.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PotatoVN.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(PotatoVN.Client.Client.ClientUtils.ParameterToMultiMap("", "timestamp", timestamp));
            if (pageIndex != null)
            {
                localVarRequestOptions.QueryParameters.Add(PotatoVN.Client.Client.ClientUtils.ParameterToMultiMap("", "pageIndex", pageIndex));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(PotatoVN.Client.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }

            // authentication (oauth2) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<GalgameDeletedDtoPagedResult>("/galgame/deleted", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GalgameDeletedGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 删除游戏 只能删除自己的游戏
        /// </summary>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="galgameId"></param>
        /// <returns></returns>
        public void GalgameGalgameIdDelete(int galgameId)
        {
            GalgameGalgameIdDeleteWithHttpInfo(galgameId);
        }

        /// <summary>
        /// 删除游戏 只能删除自己的游戏
        /// </summary>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="galgameId"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public PotatoVN.Client.Client.ApiResponse<Object> GalgameGalgameIdDeleteWithHttpInfo(int galgameId)
        {
            PotatoVN.Client.Client.RequestOptions localVarRequestOptions = new PotatoVN.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = PotatoVN.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PotatoVN.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("galgameId", PotatoVN.Client.Client.ClientUtils.ParameterToString(galgameId)); // path parameter

            // authentication (oauth2) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/galgame/{galgameId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GalgameGalgameIdDelete", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 删除游戏 只能删除自己的游戏
        /// </summary>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="galgameId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task GalgameGalgameIdDeleteAsync(int galgameId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            await GalgameGalgameIdDeleteWithHttpInfoAsync(galgameId, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// 删除游戏 只能删除自己的游戏
        /// </summary>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="galgameId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<PotatoVN.Client.Client.ApiResponse<Object>> GalgameGalgameIdDeleteWithHttpInfoAsync(int galgameId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            PotatoVN.Client.Client.RequestOptions localVarRequestOptions = new PotatoVN.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = PotatoVN.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PotatoVN.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("galgameId", PotatoVN.Client.Client.ClientUtils.ParameterToString(galgameId)); // path parameter

            // authentication (oauth2) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/galgame/{galgameId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GalgameGalgameIdDelete", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 添加游玩记录或游玩时长 若已经有当天游戏的记录，则累加上去
        /// </summary>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="galgameId"></param>
        /// <param name="playLogDto"> (optional)</param>
        /// <returns>GalgameDto</returns>
        public GalgameDto GalgameGalgameIdPlaylogPatch(int galgameId, PlayLogDto? playLogDto = default(PlayLogDto?))
        {
            PotatoVN.Client.Client.ApiResponse<GalgameDto> localVarResponse = GalgameGalgameIdPlaylogPatchWithHttpInfo(galgameId, playLogDto);
            return localVarResponse.Data;
        }

        /// <summary>
        /// 添加游玩记录或游玩时长 若已经有当天游戏的记录，则累加上去
        /// </summary>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="galgameId"></param>
        /// <param name="playLogDto"> (optional)</param>
        /// <returns>ApiResponse of GalgameDto</returns>
        public PotatoVN.Client.Client.ApiResponse<GalgameDto> GalgameGalgameIdPlaylogPatchWithHttpInfo(int galgameId, PlayLogDto? playLogDto = default(PlayLogDto?))
        {
            PotatoVN.Client.Client.RequestOptions localVarRequestOptions = new PotatoVN.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = PotatoVN.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PotatoVN.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("galgameId", PotatoVN.Client.Client.ClientUtils.ParameterToString(galgameId)); // path parameter
            localVarRequestOptions.Data = playLogDto;

            // authentication (oauth2) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Patch<GalgameDto>("/galgame/{galgameId}/playlog", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GalgameGalgameIdPlaylogPatch", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 添加游玩记录或游玩时长 若已经有当天游戏的记录，则累加上去
        /// </summary>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="galgameId"></param>
        /// <param name="playLogDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GalgameDto</returns>
        public async System.Threading.Tasks.Task<GalgameDto> GalgameGalgameIdPlaylogPatchAsync(int galgameId, PlayLogDto? playLogDto = default(PlayLogDto?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            PotatoVN.Client.Client.ApiResponse<GalgameDto> localVarResponse = await GalgameGalgameIdPlaylogPatchWithHttpInfoAsync(galgameId, playLogDto, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// 添加游玩记录或游玩时长 若已经有当天游戏的记录，则累加上去
        /// </summary>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="galgameId"></param>
        /// <param name="playLogDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GalgameDto)</returns>
        public async System.Threading.Tasks.Task<PotatoVN.Client.Client.ApiResponse<GalgameDto>> GalgameGalgameIdPlaylogPatchWithHttpInfoAsync(int galgameId, PlayLogDto? playLogDto = default(PlayLogDto?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            PotatoVN.Client.Client.RequestOptions localVarRequestOptions = new PotatoVN.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = PotatoVN.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PotatoVN.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("galgameId", PotatoVN.Client.Client.ClientUtils.ParameterToString(galgameId)); // path parameter
            localVarRequestOptions.Data = playLogDto;

            // authentication (oauth2) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PatchAsync<GalgameDto>("/galgame/{galgameId}/playlog", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GalgameGalgameIdPlaylogPatch", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 获取galgame列表 获取最后一次更新时间严格晚于给定时间戳的galgame列表
        /// </summary>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="timestamp"></param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <returns>GalgameDtoPagedResult</returns>
        public GalgameDtoPagedResult GalgameGet(long timestamp, int? pageIndex = default(int?), int? pageSize = default(int?))
        {
            PotatoVN.Client.Client.ApiResponse<GalgameDtoPagedResult> localVarResponse = GalgameGetWithHttpInfo(timestamp, pageIndex, pageSize);
            return localVarResponse.Data;
        }

        /// <summary>
        /// 获取galgame列表 获取最后一次更新时间严格晚于给定时间戳的galgame列表
        /// </summary>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="timestamp"></param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <returns>ApiResponse of GalgameDtoPagedResult</returns>
        public PotatoVN.Client.Client.ApiResponse<GalgameDtoPagedResult> GalgameGetWithHttpInfo(long timestamp, int? pageIndex = default(int?), int? pageSize = default(int?))
        {
            PotatoVN.Client.Client.RequestOptions localVarRequestOptions = new PotatoVN.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = PotatoVN.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PotatoVN.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(PotatoVN.Client.Client.ClientUtils.ParameterToMultiMap("", "timestamp", timestamp));
            if (pageIndex != null)
            {
                localVarRequestOptions.QueryParameters.Add(PotatoVN.Client.Client.ClientUtils.ParameterToMultiMap("", "pageIndex", pageIndex));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(PotatoVN.Client.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }

            // authentication (oauth2) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GalgameDtoPagedResult>("/galgame", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GalgameGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 获取galgame列表 获取最后一次更新时间严格晚于给定时间戳的galgame列表
        /// </summary>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="timestamp"></param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GalgameDtoPagedResult</returns>
        public async System.Threading.Tasks.Task<GalgameDtoPagedResult> GalgameGetAsync(long timestamp, int? pageIndex = default(int?), int? pageSize = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            PotatoVN.Client.Client.ApiResponse<GalgameDtoPagedResult> localVarResponse = await GalgameGetWithHttpInfoAsync(timestamp, pageIndex, pageSize, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// 获取galgame列表 获取最后一次更新时间严格晚于给定时间戳的galgame列表
        /// </summary>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="timestamp"></param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GalgameDtoPagedResult)</returns>
        public async System.Threading.Tasks.Task<PotatoVN.Client.Client.ApiResponse<GalgameDtoPagedResult>> GalgameGetWithHttpInfoAsync(long timestamp, int? pageIndex = default(int?), int? pageSize = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            PotatoVN.Client.Client.RequestOptions localVarRequestOptions = new PotatoVN.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = PotatoVN.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PotatoVN.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(PotatoVN.Client.Client.ClientUtils.ParameterToMultiMap("", "timestamp", timestamp));
            if (pageIndex != null)
            {
                localVarRequestOptions.QueryParameters.Add(PotatoVN.Client.Client.ClientUtils.ParameterToMultiMap("", "pageIndex", pageIndex));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(PotatoVN.Client.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }

            // authentication (oauth2) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<GalgameDtoPagedResult>("/galgame", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GalgameGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 新建或更新galgame 所有字段均可选，覆盖原字段 &lt;br /&gt;&lt;b&gt;若Id没有填，则认为是新建galgame&lt;/b&gt;&lt;br /&gt;  务必注意字段是覆盖的，意味着游玩时间记录会覆盖掉原记录，若需要追加记录请使用[PATCH] /galgame/{id}/playlog &lt;br /&gt;
        /// </summary>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="galgameUpdateDto"> (optional)</param>
        /// <returns>GalgameDto</returns>
        public GalgameDto GalgamePatch(GalgameUpdateDto? galgameUpdateDto = default(GalgameUpdateDto?))
        {
            PotatoVN.Client.Client.ApiResponse<GalgameDto> localVarResponse = GalgamePatchWithHttpInfo(galgameUpdateDto);
            return localVarResponse.Data;
        }

        /// <summary>
        /// 新建或更新galgame 所有字段均可选，覆盖原字段 &lt;br /&gt;&lt;b&gt;若Id没有填，则认为是新建galgame&lt;/b&gt;&lt;br /&gt;  务必注意字段是覆盖的，意味着游玩时间记录会覆盖掉原记录，若需要追加记录请使用[PATCH] /galgame/{id}/playlog &lt;br /&gt;
        /// </summary>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="galgameUpdateDto"> (optional)</param>
        /// <returns>ApiResponse of GalgameDto</returns>
        public PotatoVN.Client.Client.ApiResponse<GalgameDto> GalgamePatchWithHttpInfo(GalgameUpdateDto? galgameUpdateDto = default(GalgameUpdateDto?))
        {
            PotatoVN.Client.Client.RequestOptions localVarRequestOptions = new PotatoVN.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = PotatoVN.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PotatoVN.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = galgameUpdateDto;

            // authentication (oauth2) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Patch<GalgameDto>("/galgame", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GalgamePatch", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 新建或更新galgame 所有字段均可选，覆盖原字段 &lt;br /&gt;&lt;b&gt;若Id没有填，则认为是新建galgame&lt;/b&gt;&lt;br /&gt;  务必注意字段是覆盖的，意味着游玩时间记录会覆盖掉原记录，若需要追加记录请使用[PATCH] /galgame/{id}/playlog &lt;br /&gt;
        /// </summary>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="galgameUpdateDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GalgameDto</returns>
        public async System.Threading.Tasks.Task<GalgameDto> GalgamePatchAsync(GalgameUpdateDto? galgameUpdateDto = default(GalgameUpdateDto?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            PotatoVN.Client.Client.ApiResponse<GalgameDto> localVarResponse = await GalgamePatchWithHttpInfoAsync(galgameUpdateDto, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// 新建或更新galgame 所有字段均可选，覆盖原字段 &lt;br /&gt;&lt;b&gt;若Id没有填，则认为是新建galgame&lt;/b&gt;&lt;br /&gt;  务必注意字段是覆盖的，意味着游玩时间记录会覆盖掉原记录，若需要追加记录请使用[PATCH] /galgame/{id}/playlog &lt;br /&gt;
        /// </summary>
        /// <exception cref="PotatoVN.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="galgameUpdateDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GalgameDto)</returns>
        public async System.Threading.Tasks.Task<PotatoVN.Client.Client.ApiResponse<GalgameDto>> GalgamePatchWithHttpInfoAsync(GalgameUpdateDto? galgameUpdateDto = default(GalgameUpdateDto?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            PotatoVN.Client.Client.RequestOptions localVarRequestOptions = new PotatoVN.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = PotatoVN.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PotatoVN.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = galgameUpdateDto;

            // authentication (oauth2) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PatchAsync<GalgameDto>("/galgame", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GalgamePatch", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
