/*
 * PotatoVN.Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using PotatoVN.Client.Client;
using PotatoVN.Client.Api;
// uncomment below to import models
//using PotatoVN.Client.Model;

namespace PotatoVN.Client.Test.Api
{
    /// <summary>
    ///  Class for testing BangumiApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class BangumiApiTests : IDisposable
    {
        private BangumiApi instance;

        public BangumiApiTests()
        {
            instance = new BangumiApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BangumiApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' BangumiApi
            //Assert.IsType<BangumiApi>(instance);
        }

        /// <summary>
        /// Test BangumiOauthGet
        /// </summary>
        [Fact]
        public void BangumiOauthGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string code = null;
            //var response = instance.BangumiOauthGet(code);
            //Assert.IsType<BangumiToken>(response);
        }

        /// <summary>
        /// Test BangumiRefreshGet
        /// </summary>
        [Fact]
        public void BangumiRefreshGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string refreshToken = null;
            //var response = instance.BangumiRefreshGet(refreshToken);
            //Assert.IsType<BangumiToken>(response);
        }
    }
}
