/*
 * PotatoVN.Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using PotatoVN.Client.Client;
using PotatoVN.Client.Api;
// uncomment below to import models
//using PotatoVN.Client.Model;

namespace PotatoVN.Client.Test.Api
{
    /// <summary>
    ///  Class for testing OssApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class OssApiTests : IDisposable
    {
        private OssApi instance;

        public OssApiTests()
        {
            instance = new OssApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OssApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' OssApi
            //Assert.IsType<OssApi>(instance);
        }

        /// <summary>
        /// Test OssGetGet
        /// </summary>
        [Fact]
        public void OssGetGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? objectFullName = null;
            //var response = instance.OssGetGet(objectFullName);
            //Assert.IsType<string>(response);
        }

        /// <summary>
        /// Test OssPutGet
        /// </summary>
        [Fact]
        public void OssPutGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? objectFullName = null;
            //long? requireSpace = null;
            //var response = instance.OssPutGet(objectFullName, requireSpace);
            //Assert.IsType<string>(response);
        }

        /// <summary>
        /// Test OssUpdatePut
        /// </summary>
        [Fact]
        public void OssUpdatePutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? objectFullName = null;
            //var response = instance.OssUpdatePut(objectFullName);
            //Assert.IsType<UserDto>(response);
        }
    }
}
