/*
 * PotatoVN.Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using PotatoVN.Client.Client;
using PotatoVN.Client.Api;
// uncomment below to import models
//using PotatoVN.Client.Model;

namespace PotatoVN.Client.Test.Api
{
    /// <summary>
    ///  Class for testing ServerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ServerApiTests : IDisposable
    {
        private ServerApi instance;

        public ServerApiTests()
        {
            instance = new ServerApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServerApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ServerApi
            //Assert.IsType<ServerApi>(instance);
        }

        /// <summary>
        /// Test ServerInfoGet
        /// </summary>
        [Fact]
        public void ServerInfoGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ServerInfoGet();
            //Assert.IsType<ServerInfoDto>(response);
        }
    }
}
