/*
 * PotatoVN.Server
 *
 * PotatoVN 同步服务器 最新更新：支持staff同步
 *
 * The version of the OpenAPI document: v1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PotatoVN.Client.Model;
using PotatoVN.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PotatoVN.Client.Test.Model
{
    /// <summary>
    ///  Class for testing Career
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CareerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Career
        //private Career instance;

        public CareerTests()
        {
            // TODO uncomment below to create an instance of Career
            //instance = new Career();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Career
        /// </summary>
        [Fact]
        public void CareerInstanceTest()
        {
            // TODO uncomment below to test "IsType" Career
            //Assert.IsType<Career>(instance);
        }
    }
}
