/*
 * PotatoVN.Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PotatoVN.Client.Model;
using PotatoVN.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PotatoVN.Client.Test.Model
{
    /// <summary>
    ///  Class for testing CharacterDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CharacterDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CharacterDto
        //private CharacterDto instance;

        public CharacterDtoTests()
        {
            // TODO uncomment below to create an instance of CharacterDto
            //instance = new CharacterDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CharacterDto
        /// </summary>
        [Fact]
        public void CharacterDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CharacterDto
            //Assert.IsType<CharacterDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Relation'
        /// </summary>
        [Fact]
        public void RelationTest()
        {
            // TODO unit test for the property 'Relation'
        }

        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Fact]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }

        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Fact]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }

        /// <summary>
        /// Test the property 'BirthYear'
        /// </summary>
        [Fact]
        public void BirthYearTest()
        {
            // TODO unit test for the property 'BirthYear'
        }

        /// <summary>
        /// Test the property 'BirthMonth'
        /// </summary>
        [Fact]
        public void BirthMonthTest()
        {
            // TODO unit test for the property 'BirthMonth'
        }

        /// <summary>
        /// Test the property 'BirthDay'
        /// </summary>
        [Fact]
        public void BirthDayTest()
        {
            // TODO unit test for the property 'BirthDay'
        }

        /// <summary>
        /// Test the property 'BloodType'
        /// </summary>
        [Fact]
        public void BloodTypeTest()
        {
            // TODO unit test for the property 'BloodType'
        }

        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }

        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Fact]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }

        /// <summary>
        /// Test the property 'ThreeSize'
        /// </summary>
        [Fact]
        public void ThreeSizeTest()
        {
            // TODO unit test for the property 'ThreeSize'
        }

        /// <summary>
        /// Test the property 'ImageUrl'
        /// </summary>
        [Fact]
        public void ImageUrlTest()
        {
            // TODO unit test for the property 'ImageUrl'
        }

        /// <summary>
        /// Test the property 'PreviewImageUrl'
        /// </summary>
        [Fact]
        public void PreviewImageUrlTest()
        {
            // TODO unit test for the property 'PreviewImageUrl'
        }
    }
}
