/*
 * PotatoVN.Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PotatoVN.Client.Model;
using PotatoVN.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PotatoVN.Client.Test.Model
{
    /// <summary>
    ///  Class for testing GalgameUpdateDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GalgameUpdateDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GalgameUpdateDto
        //private GalgameUpdateDto instance;

        public GalgameUpdateDtoTests()
        {
            // TODO uncomment below to create an instance of GalgameUpdateDto
            //instance = new GalgameUpdateDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GalgameUpdateDto
        /// </summary>
        [Fact]
        public void GalgameUpdateDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" GalgameUpdateDto
            //Assert.IsType<GalgameUpdateDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'BgmId'
        /// </summary>
        [Fact]
        public void BgmIdTest()
        {
            // TODO unit test for the property 'BgmId'
        }

        /// <summary>
        /// Test the property 'VndbId'
        /// </summary>
        [Fact]
        public void VndbIdTest()
        {
            // TODO unit test for the property 'VndbId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'CnName'
        /// </summary>
        [Fact]
        public void CnNameTest()
        {
            // TODO unit test for the property 'CnName'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Developer'
        /// </summary>
        [Fact]
        public void DeveloperTest()
        {
            // TODO unit test for the property 'Developer'
        }

        /// <summary>
        /// Test the property 'ExpectedPlayTime'
        /// </summary>
        [Fact]
        public void ExpectedPlayTimeTest()
        {
            // TODO unit test for the property 'ExpectedPlayTime'
        }

        /// <summary>
        /// Test the property 'Rating'
        /// </summary>
        [Fact]
        public void RatingTest()
        {
            // TODO unit test for the property 'Rating'
        }

        /// <summary>
        /// Test the property 'ReleaseDateTimeStamp'
        /// </summary>
        [Fact]
        public void ReleaseDateTimeStampTest()
        {
            // TODO unit test for the property 'ReleaseDateTimeStamp'
        }

        /// <summary>
        /// Test the property 'ImageLoc'
        /// </summary>
        [Fact]
        public void ImageLocTest()
        {
            // TODO unit test for the property 'ImageLoc'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

        /// <summary>
        /// Test the property 'TotalPlayTime'
        /// </summary>
        [Fact]
        public void TotalPlayTimeTest()
        {
            // TODO unit test for the property 'TotalPlayTime'
        }

        /// <summary>
        /// Test the property 'PlayType'
        /// </summary>
        [Fact]
        public void PlayTypeTest()
        {
            // TODO unit test for the property 'PlayType'
        }

        /// <summary>
        /// Test the property 'PlayTime'
        /// </summary>
        [Fact]
        public void PlayTimeTest()
        {
            // TODO unit test for the property 'PlayTime'
        }

        /// <summary>
        /// Test the property 'Comment'
        /// </summary>
        [Fact]
        public void CommentTest()
        {
            // TODO unit test for the property 'Comment'
        }

        /// <summary>
        /// Test the property 'MyRate'
        /// </summary>
        [Fact]
        public void MyRateTest()
        {
            // TODO unit test for the property 'MyRate'
        }

        /// <summary>
        /// Test the property 'PrivateComment'
        /// </summary>
        [Fact]
        public void PrivateCommentTest()
        {
            // TODO unit test for the property 'PrivateComment'
        }
    }
}
