/*
 * PotatoVN.Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PotatoVN.Client.Model;
using PotatoVN.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PotatoVN.Client.Test.Model
{
    /// <summary>
    ///  Class for testing GalgameDeletedDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GalgameDeletedDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GalgameDeletedDto
        //private GalgameDeletedDto instance;

        public GalgameDeletedDtoTests()
        {
            // TODO uncomment below to create an instance of GalgameDeletedDto
            //instance = new GalgameDeletedDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GalgameDeletedDto
        /// </summary>
        [Fact]
        public void GalgameDeletedDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" GalgameDeletedDto
            //Assert.IsType<GalgameDeletedDto>(instance);
        }

        /// <summary>
        /// Test the property 'GalgameId'
        /// </summary>
        [Fact]
        public void GalgameIdTest()
        {
            // TODO unit test for the property 'GalgameId'
        }

        /// <summary>
        /// Test the property 'DeleteTimeStamp'
        /// </summary>
        [Fact]
        public void DeleteTimeStampTest()
        {
            // TODO unit test for the property 'DeleteTimeStamp'
        }
    }
}
