/*
 * PotatoVN.Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PotatoVN.Client.Model;
using PotatoVN.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PotatoVN.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PlayLogDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PlayLogDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PlayLogDto
        //private PlayLogDto instance;

        public PlayLogDtoTests()
        {
            // TODO uncomment below to create an instance of PlayLogDto
            //instance = new PlayLogDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PlayLogDto
        /// </summary>
        [Fact]
        public void PlayLogDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" PlayLogDto
            //Assert.IsType<PlayLogDto>(instance);
        }

        /// <summary>
        /// Test the property 'DateTimeStamp'
        /// </summary>
        [Fact]
        public void DateTimeStampTest()
        {
            // TODO unit test for the property 'DateTimeStamp'
        }

        /// <summary>
        /// Test the property 'Minute'
        /// </summary>
        [Fact]
        public void MinuteTest()
        {
            // TODO unit test for the property 'Minute'
        }
    }
}
