/*
 * PotatoVN.Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PotatoVN.Client.Model;
using PotatoVN.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PotatoVN.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PlayType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PlayTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PlayType
        //private PlayType instance;

        public PlayTypeTests()
        {
            // TODO uncomment below to create an instance of PlayType
            //instance = new PlayType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PlayType
        /// </summary>
        [Fact]
        public void PlayTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" PlayType
            //Assert.IsType<PlayType>(instance);
        }
    }
}
