/*
 * PotatoVN.Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PotatoVN.Client.Model;
using PotatoVN.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PotatoVN.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ServerInfoDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServerInfoDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServerInfoDto
        //private ServerInfoDto instance;

        public ServerInfoDtoTests()
        {
            // TODO uncomment below to create an instance of ServerInfoDto
            //instance = new ServerInfoDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServerInfoDto
        /// </summary>
        [Fact]
        public void ServerInfoDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServerInfoDto
            //Assert.IsType<ServerInfoDto>(instance);
        }

        /// <summary>
        /// Test the property 'BangumiOAuth2Enable'
        /// </summary>
        [Fact]
        public void BangumiOAuth2EnableTest()
        {
            // TODO unit test for the property 'BangumiOAuth2Enable'
        }

        /// <summary>
        /// Test the property 'DefaultLoginEnable'
        /// </summary>
        [Fact]
        public void DefaultLoginEnableTest()
        {
            // TODO unit test for the property 'DefaultLoginEnable'
        }

        /// <summary>
        /// Test the property 'BangumiLoginEnable'
        /// </summary>
        [Fact]
        public void BangumiLoginEnableTest()
        {
            // TODO unit test for the property 'BangumiLoginEnable'
        }
    }
}
