/*
 * PotatoVN.Server
 *
 * PotatoVN 同步服务器 最新更新：支持staff同步
 *
 * The version of the OpenAPI document: v1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PotatoVN.Client.Model;
using PotatoVN.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PotatoVN.Client.Test.Model
{
    /// <summary>
    ///  Class for testing StaffUpdateDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StaffUpdateDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StaffUpdateDto
        //private StaffUpdateDto instance;

        public StaffUpdateDtoTests()
        {
            // TODO uncomment below to create an instance of StaffUpdateDto
            //instance = new StaffUpdateDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StaffUpdateDto
        /// </summary>
        [Fact]
        public void StaffUpdateDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" StaffUpdateDto
            //Assert.IsType<StaffUpdateDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'IsDeleted'
        /// </summary>
        [Fact]
        public void IsDeletedTest()
        {
            // TODO unit test for the property 'IsDeleted'
        }

        /// <summary>
        /// Test the property 'BgmId'
        /// </summary>
        [Fact]
        public void BgmIdTest()
        {
            // TODO unit test for the property 'BgmId'
        }

        /// <summary>
        /// Test the property 'VndbId'
        /// </summary>
        [Fact]
        public void VndbIdTest()
        {
            // TODO unit test for the property 'VndbId'
        }

        /// <summary>
        /// Test the property 'YmgalId'
        /// </summary>
        [Fact]
        public void YmgalIdTest()
        {
            // TODO unit test for the property 'YmgalId'
        }

        /// <summary>
        /// Test the property 'JapaneseName'
        /// </summary>
        [Fact]
        public void JapaneseNameTest()
        {
            // TODO unit test for the property 'JapaneseName'
        }

        /// <summary>
        /// Test the property 'EnglishName'
        /// </summary>
        [Fact]
        public void EnglishNameTest()
        {
            // TODO unit test for the property 'EnglishName'
        }

        /// <summary>
        /// Test the property 'ChineseName'
        /// </summary>
        [Fact]
        public void ChineseNameTest()
        {
            // TODO unit test for the property 'ChineseName'
        }

        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Fact]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'BirthDateTimestamp'
        /// </summary>
        [Fact]
        public void BirthDateTimestampTest()
        {
            // TODO unit test for the property 'BirthDateTimestamp'
        }

        /// <summary>
        /// Test the property 'ImageLoc'
        /// </summary>
        [Fact]
        public void ImageLocTest()
        {
            // TODO unit test for the property 'ImageLoc'
        }

        /// <summary>
        /// Test the property 'StaffGames'
        /// </summary>
        [Fact]
        public void StaffGamesTest()
        {
            // TODO unit test for the property 'StaffGames'
        }
    }
}
