/*
 * PotatoVN.Server
 *
 * PotatoVN 同步服务器 最新更新：支持staff同步
 *
 * The version of the OpenAPI document: v1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PotatoVN.Client.Model;
using PotatoVN.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PotatoVN.Client.Test.Model
{
    /// <summary>
    ///  Class for testing StaffDtoPagedResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StaffDtoPagedResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StaffDtoPagedResult
        //private StaffDtoPagedResult instance;

        public StaffDtoPagedResultTests()
        {
            // TODO uncomment below to create an instance of StaffDtoPagedResult
            //instance = new StaffDtoPagedResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StaffDtoPagedResult
        /// </summary>
        [Fact]
        public void StaffDtoPagedResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" StaffDtoPagedResult
            //Assert.IsType<StaffDtoPagedResult>(instance);
        }

        /// <summary>
        /// Test the property 'Cnt'
        /// </summary>
        [Fact]
        public void CntTest()
        {
            // TODO unit test for the property 'Cnt'
        }

        /// <summary>
        /// Test the property 'PageCnt'
        /// </summary>
        [Fact]
        public void PageCntTest()
        {
            // TODO unit test for the property 'PageCnt'
        }

        /// <summary>
        /// Test the property 'PageIndex'
        /// </summary>
        [Fact]
        public void PageIndexTest()
        {
            // TODO unit test for the property 'PageIndex'
        }

        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
    }
}
