/*
 * PotatoVN.Server
 *
 * PotatoVN 同步服务器 最新更新：支持staff同步
 *
 * The version of the OpenAPI document: v1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PotatoVN.Client.Model;
using PotatoVN.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PotatoVN.Client.Test.Model
{
    /// <summary>
    ///  Class for testing StaffGameUpdateDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StaffGameUpdateDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StaffGameUpdateDto
        //private StaffGameUpdateDto instance;

        public StaffGameUpdateDtoTests()
        {
            // TODO uncomment below to create an instance of StaffGameUpdateDto
            //instance = new StaffGameUpdateDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StaffGameUpdateDto
        /// </summary>
        [Fact]
        public void StaffGameUpdateDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" StaffGameUpdateDto
            //Assert.IsType<StaffGameUpdateDto>(instance);
        }

        /// <summary>
        /// Test the property 'GameId'
        /// </summary>
        [Fact]
        public void GameIdTest()
        {
            // TODO unit test for the property 'GameId'
        }

        /// <summary>
        /// Test the property 'Relation'
        /// </summary>
        [Fact]
        public void RelationTest()
        {
            // TODO unit test for the property 'Relation'
        }
    }
}
