/*
 * PotatoVN.Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PotatoVN.Client.Model;
using PotatoVN.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PotatoVN.Client.Test.Model
{
    /// <summary>
    ///  Class for testing UserDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserDto
        //private UserDto instance;

        public UserDtoTests()
        {
            // TODO uncomment below to create an instance of UserDto
            //instance = new UserDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserDto
        /// </summary>
        [Fact]
        public void UserDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserDto
            //Assert.IsType<UserDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Fact]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }

        /// <summary>
        /// Test the property 'UserDisplayName'
        /// </summary>
        [Fact]
        public void UserDisplayNameTest()
        {
            // TODO unit test for the property 'UserDisplayName'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'BangumiId'
        /// </summary>
        [Fact]
        public void BangumiIdTest()
        {
            // TODO unit test for the property 'BangumiId'
        }

        /// <summary>
        /// Test the property 'Avatar'
        /// </summary>
        [Fact]
        public void AvatarTest()
        {
            // TODO unit test for the property 'Avatar'
        }

        /// <summary>
        /// Test the property 'UsedSpace'
        /// </summary>
        [Fact]
        public void UsedSpaceTest()
        {
            // TODO unit test for the property 'UsedSpace'
        }

        /// <summary>
        /// Test the property 'TotalSpace'
        /// </summary>
        [Fact]
        public void TotalSpaceTest()
        {
            // TODO unit test for the property 'TotalSpace'
        }

        /// <summary>
        /// Test the property 'LastGalChangedTimeStamp'
        /// </summary>
        [Fact]
        public void LastGalChangedTimeStampTest()
        {
            // TODO unit test for the property 'LastGalChangedTimeStamp'
        }
    }
}
