/*
 * PotatoVN.Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PotatoVN.Client.Model;
using PotatoVN.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PotatoVN.Client.Test.Model
{
    /// <summary>
    ///  Class for testing UserType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserType
        //private UserType instance;

        public UserTypeTests()
        {
            // TODO uncomment below to create an instance of UserType
            //instance = new UserType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserType
        /// </summary>
        [Fact]
        public void UserTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserType
            //Assert.IsType<UserType>(instance);
        }
    }
}
