/*
 * PotatoVN.Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PotatoVN.Client.Model;
using PotatoVN.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PotatoVN.Client.Test.Model
{
    /// <summary>
    ///  Class for testing UserModifyDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserModifyDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserModifyDto
        //private UserModifyDto instance;

        public UserModifyDtoTests()
        {
            // TODO uncomment below to create an instance of UserModifyDto
            //instance = new UserModifyDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserModifyDto
        /// </summary>
        [Fact]
        public void UserModifyDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserModifyDto
            //Assert.IsType<UserModifyDto>(instance);
        }

        /// <summary>
        /// Test the property 'UserDisplayName'
        /// </summary>
        [Fact]
        public void UserDisplayNameTest()
        {
            // TODO unit test for the property 'UserDisplayName'
        }

        /// <summary>
        /// Test the property 'AvatarLoc'
        /// </summary>
        [Fact]
        public void AvatarLocTest()
        {
            // TODO unit test for the property 'AvatarLoc'
        }

        /// <summary>
        /// Test the property 'OldPassword'
        /// </summary>
        [Fact]
        public void OldPasswordTest()
        {
            // TODO unit test for the property 'OldPassword'
        }

        /// <summary>
        /// Test the property 'NewPassword'
        /// </summary>
        [Fact]
        public void NewPasswordTest()
        {
            // TODO unit test for the property 'NewPassword'
        }
    }
}
