/*
 * PotatoVN.Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PotatoVN.Client.Model;
using PotatoVN.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PotatoVN.Client.Test.Model
{
    /// <summary>
    ///  Class for testing UserWithTokenDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserWithTokenDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserWithTokenDto
        //private UserWithTokenDto instance;

        public UserWithTokenDtoTests()
        {
            // TODO uncomment below to create an instance of UserWithTokenDto
            //instance = new UserWithTokenDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserWithTokenDto
        /// </summary>
        [Fact]
        public void UserWithTokenDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserWithTokenDto
            //Assert.IsType<UserWithTokenDto>(instance);
        }

        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }

        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }

        /// <summary>
        /// Test the property 'Expire'
        /// </summary>
        [Fact]
        public void ExpireTest()
        {
            // TODO unit test for the property 'Expire'
        }
    }
}
