/*
 * PotatoVN.Server
 *
 * PotatoVN 同步服务器 最新更新：支持staff同步
 *
 * The version of the OpenAPI document: v1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = PotatoVN.Client.Client.FileParameter;
using OpenAPIDateConverter = PotatoVN.Client.Client.OpenAPIDateConverter;

namespace PotatoVN.Client.Model
{
    /// <summary>
    /// CharacterUpdateDto
    /// </summary>
    [DataContract(Name = "CharacterUpdateDto")]
    public partial class CharacterUpdateDto : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Gender
        /// </summary>
        [DataMember(Name = "gender", EmitDefaultValue = false)]
        public Gender? Gender { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CharacterUpdateDto" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="name">name.</param>
        /// <param name="relation">relation.</param>
        /// <param name="summary">summary.</param>
        /// <param name="gender">gender.</param>
        /// <param name="birthYear">birthYear.</param>
        /// <param name="birthMonth">birthMonth.</param>
        /// <param name="birthDay">birthDay.</param>
        /// <param name="bloodType">bloodType.</param>
        /// <param name="height">height.</param>
        /// <param name="weight">weight.</param>
        /// <param name="threeSize">threeSize.</param>
        /// <param name="imageLoc">imageLoc.</param>
        /// <param name="previewImageLoc">previewImageLoc.</param>
        public CharacterUpdateDto(int id = default(int), string name = default(string), string relation = default(string), string summary = default(string), Gender? gender = default(Gender?), int birthYear = default(int), int birthMonth = default(int), int birthDay = default(int), string bloodType = default(string), string height = default(string), string weight = default(string), string threeSize = default(string), string imageLoc = default(string), string previewImageLoc = default(string))
        {
            this.Id = id;
            this.Name = name;
            this.Relation = relation;
            this.Summary = summary;
            this.Gender = gender;
            this.BirthYear = birthYear;
            this.BirthMonth = birthMonth;
            this.BirthDay = birthDay;
            this.BloodType = bloodType;
            this.Height = height;
            this.Weight = weight;
            this.ThreeSize = threeSize;
            this.ImageLoc = imageLoc;
            this.PreviewImageLoc = previewImageLoc;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Relation
        /// </summary>
        [DataMember(Name = "relation", EmitDefaultValue = true)]
        public string Relation { get; set; }

        /// <summary>
        /// Gets or Sets Summary
        /// </summary>
        [DataMember(Name = "summary", EmitDefaultValue = true)]
        public string Summary { get; set; }

        /// <summary>
        /// Gets or Sets BirthYear
        /// </summary>
        [DataMember(Name = "birthYear", EmitDefaultValue = false)]
        public int BirthYear { get; set; }

        /// <summary>
        /// Gets or Sets BirthMonth
        /// </summary>
        [DataMember(Name = "birthMonth", EmitDefaultValue = false)]
        public int BirthMonth { get; set; }

        /// <summary>
        /// Gets or Sets BirthDay
        /// </summary>
        [DataMember(Name = "birthDay", EmitDefaultValue = false)]
        public int BirthDay { get; set; }

        /// <summary>
        /// Gets or Sets BloodType
        /// </summary>
        [DataMember(Name = "bloodType", EmitDefaultValue = true)]
        public string BloodType { get; set; }

        /// <summary>
        /// Gets or Sets Height
        /// </summary>
        [DataMember(Name = "height", EmitDefaultValue = true)]
        public string Height { get; set; }

        /// <summary>
        /// Gets or Sets Weight
        /// </summary>
        [DataMember(Name = "weight", EmitDefaultValue = true)]
        public string Weight { get; set; }

        /// <summary>
        /// Gets or Sets ThreeSize
        /// </summary>
        [DataMember(Name = "threeSize", EmitDefaultValue = true)]
        public string ThreeSize { get; set; }

        /// <summary>
        /// Gets or Sets ImageLoc
        /// </summary>
        [DataMember(Name = "imageLoc", EmitDefaultValue = true)]
        public string ImageLoc { get; set; }

        /// <summary>
        /// Gets or Sets PreviewImageLoc
        /// </summary>
        [DataMember(Name = "previewImageLoc", EmitDefaultValue = true)]
        public string PreviewImageLoc { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CharacterUpdateDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Relation: ").Append(Relation).Append("\n");
            sb.Append("  Summary: ").Append(Summary).Append("\n");
            sb.Append("  Gender: ").Append(Gender).Append("\n");
            sb.Append("  BirthYear: ").Append(BirthYear).Append("\n");
            sb.Append("  BirthMonth: ").Append(BirthMonth).Append("\n");
            sb.Append("  BirthDay: ").Append(BirthDay).Append("\n");
            sb.Append("  BloodType: ").Append(BloodType).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  Weight: ").Append(Weight).Append("\n");
            sb.Append("  ThreeSize: ").Append(ThreeSize).Append("\n");
            sb.Append("  ImageLoc: ").Append(ImageLoc).Append("\n");
            sb.Append("  PreviewImageLoc: ").Append(PreviewImageLoc).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 200)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 200.", new [] { "Name" });
            }

            // Relation (string) maxLength
            if (this.Relation != null && this.Relation.Length > 200)
            {
                yield return new ValidationResult("Invalid value for Relation, length must be less than 200.", new [] { "Relation" });
            }

            // Summary (string) maxLength
            if (this.Summary != null && this.Summary.Length > 10000)
            {
                yield return new ValidationResult("Invalid value for Summary, length must be less than 10000.", new [] { "Summary" });
            }

            // BloodType (string) maxLength
            if (this.BloodType != null && this.BloodType.Length > 50)
            {
                yield return new ValidationResult("Invalid value for BloodType, length must be less than 50.", new [] { "BloodType" });
            }

            // Height (string) maxLength
            if (this.Height != null && this.Height.Length > 50)
            {
                yield return new ValidationResult("Invalid value for Height, length must be less than 50.", new [] { "Height" });
            }

            // Weight (string) maxLength
            if (this.Weight != null && this.Weight.Length > 50)
            {
                yield return new ValidationResult("Invalid value for Weight, length must be less than 50.", new [] { "Weight" });
            }

            // ThreeSize (string) maxLength
            if (this.ThreeSize != null && this.ThreeSize.Length > 50)
            {
                yield return new ValidationResult("Invalid value for ThreeSize, length must be less than 50.", new [] { "ThreeSize" });
            }

            yield break;
        }
    }

}
