/*
 * PotatoVN.Server
 *
 * PotatoVN 同步服务器 最新更新：galgame新增playcount字段
 *
 * The version of the OpenAPI document: v1.9+e6eef47b6566802324035dddd46b62dd41d90b75
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = PotatoVN.Client.Client.FileParameter;
using OpenAPIDateConverter = PotatoVN.Client.Client.OpenAPIDateConverter;

namespace PotatoVN.Client.Model
{
    /// <summary>
    /// GalgameDeletedDtoPagedResult
    /// </summary>
    [DataContract(Name = "GalgameDeletedDtoPagedResult")]
    public partial class GalgameDeletedDtoPagedResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GalgameDeletedDtoPagedResult" /> class.
        /// </summary>
        /// <param name="cnt">cnt.</param>
        /// <param name="pageCnt">pageCnt.</param>
        /// <param name="pageIndex">pageIndex.</param>
        /// <param name="pageSize">pageSize.</param>
        /// <param name="items">items.</param>
        public GalgameDeletedDtoPagedResult(int cnt = default, int pageCnt = default, int pageIndex = default, int pageSize = default, List<GalgameDeletedDto> items = default)
        {
            this.Cnt = cnt;
            this.PageCnt = pageCnt;
            this.PageIndex = pageIndex;
            this.PageSize = pageSize;
            this.Items = items;
        }

        /// <summary>
        /// Gets or Sets Cnt
        /// </summary>
        [DataMember(Name = "cnt", EmitDefaultValue = false)]
        public int Cnt { get; set; }

        /// <summary>
        /// Gets or Sets PageCnt
        /// </summary>
        [DataMember(Name = "pageCnt", EmitDefaultValue = false)]
        public int PageCnt { get; set; }

        /// <summary>
        /// Gets or Sets PageIndex
        /// </summary>
        [DataMember(Name = "pageIndex", EmitDefaultValue = false)]
        public int PageIndex { get; set; }

        /// <summary>
        /// Gets or Sets PageSize
        /// </summary>
        [DataMember(Name = "pageSize", EmitDefaultValue = false)]
        public int PageSize { get; set; }

        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        [DataMember(Name = "items", EmitDefaultValue = true)]
        public List<GalgameDeletedDto> Items { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GalgameDeletedDtoPagedResult {\n");
            sb.Append("  Cnt: ").Append(Cnt).Append("\n");
            sb.Append("  PageCnt: ").Append(PageCnt).Append("\n");
            sb.Append("  PageIndex: ").Append(PageIndex).Append("\n");
            sb.Append("  PageSize: ").Append(PageSize).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
