/*
 * PotatoVN.Server
 *
 * PotatoVN 同步服务器 最新更新：galgame新增playcount字段
 *
 * The version of the OpenAPI document: v1.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = PotatoVN.Client.Client.FileParameter;
using OpenAPIDateConverter = PotatoVN.Client.Client.OpenAPIDateConverter;

namespace PotatoVN.Client.Model
{
    /// <summary>
    /// PlayLogDto
    /// </summary>
    [DataContract(Name = "PlayLogDto")]
    public partial class PlayLogDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayLogDto" /> class.
        /// </summary>
        /// <param name="dateTimeStamp">游玩日期当天0点0分的时间戳.</param>
        /// <param name="minute">minute.</param>
        public PlayLogDto(long dateTimeStamp = default, int minute = default)
        {
            this.DateTimeStamp = dateTimeStamp;
            this.Minute = minute;
        }

        /// <summary>
        /// 游玩日期当天0点0分的时间戳
        /// </summary>
        /// <value>游玩日期当天0点0分的时间戳</value>
        [DataMember(Name = "dateTimeStamp", EmitDefaultValue = false)]
        public long DateTimeStamp { get; set; }

        /// <summary>
        /// Gets or Sets Minute
        /// </summary>
        [DataMember(Name = "minute", EmitDefaultValue = false)]
        public int Minute { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlayLogDto {\n");
            sb.Append("  DateTimeStamp: ").Append(DateTimeStamp).Append("\n");
            sb.Append("  Minute: ").Append(Minute).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
