/*
 * PotatoVN.Server
 *
 * PotatoVN 同步服务器 最新更新：galgame新增playcount字段
 *
 * The version of the OpenAPI document: v1.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = PotatoVN.Client.Client.FileParameter;
using OpenAPIDateConverter = PotatoVN.Client.Client.OpenAPIDateConverter;

namespace PotatoVN.Client.Model
{
    /// <summary>
    /// UserLoginViaBgmDto
    /// </summary>
    [DataContract(Name = "UserLoginViaBgmDto")]
    public partial class UserLoginViaBgmDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserLoginViaBgmDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UserLoginViaBgmDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UserLoginViaBgmDto" /> class.
        /// </summary>
        /// <param name="bgmToken">bangumi token (required).</param>
        public UserLoginViaBgmDto(string bgmToken = default)
        {
            // to ensure "bgmToken" is required (not null)
            if (bgmToken == null)
            {
                throw new ArgumentNullException("bgmToken is a required property for UserLoginViaBgmDto and cannot be null");
            }
            this.BgmToken = bgmToken;
        }

        /// <summary>
        /// bangumi token
        /// </summary>
        /// <value>bangumi token</value>
        [DataMember(Name = "bgmToken", IsRequired = true, EmitDefaultValue = true)]
        public string BgmToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserLoginViaBgmDto {\n");
            sb.Append("  BgmToken: ").Append(BgmToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // BgmToken (string) minLength
            if (this.BgmToken != null && this.BgmToken.Length < 1)
            {
                yield return new ValidationResult("Invalid value for BgmToken, length must be greater than 1.", new [] { "BgmToken" });
            }

            yield break;
        }
    }

}
